from plato.db.core import get_recent_conversations, save_conversation, clear_conversations
from plato.db.soul import get_soul_doc, add_soul_entry, supersede_soul_entry, update_soul_entry, format_soul_doc
from plato.db.ideas import store_idea, park_idea, get_ideas, resolve_idea, format_ideas
from plato.db.projects import (
    create_project, get_projects, get_project_by_slug, update_project_status,
    add_project_goal, achieve_goal, get_project_goals,
    log_work, get_project_logs, get_project_summary,
    format_projects_summary, format_project_detail,
)
from plato.db.schedule import (
    save_pending_plan, get_pending_plan, approve_pending_plan, reject_pending_plan,
    save_schedule_event, report_deviation, cancel_evening_schedule_events,
    cancel_schedule_event, update_schedule_event,
    get_schedule_for_date, get_schedule_for_week, format_todays_schedule,
)
from plato.db.fitness import (
    get_current_block, create_override_block,
    log_session, get_or_create_session, get_recent_sessions,
    log_exercise, log_exercises_bulk, get_last_weight_for_exercise,
    create_modification, get_active_modifications,
    log_weigh_in, get_weight_trend,
    log_daily_nutrition, log_nutrition_batch, get_nutrition_averages, get_daily_nutrition,
    log_sleep, get_sleep_average,
    get_active_deload_cycle, start_deload_cycle, increment_deload_week, complete_deload,
    format_fitness_summary, format_fitness_detail, get_fitness_prompt,
    TRAINING_SPLIT, DAY_WEEKDAY_MAP,
)

__all__ = [
    "get_recent_conversations",
    "save_conversation",
    "clear_conversations",
    "get_soul_doc",
    "add_soul_entry",
    "supersede_soul_entry",
    "update_soul_entry",
    "format_soul_doc",
    "store_idea",
    "park_idea",
    "get_ideas",
    "resolve_idea",
    "format_ideas",
    "create_project",
    "get_projects",
    "get_project_by_slug",
    "update_project_status",
    "add_project_goal",
    "achieve_goal",
    "get_project_goals",
    "log_work",
    "get_project_logs",
    "get_project_summary",
    "format_projects_summary",
    "format_project_detail",
    "save_pending_plan",
    "get_pending_plan",
    "approve_pending_plan",
    "reject_pending_plan",
    "save_schedule_event",
    "report_deviation",
    "cancel_evening_schedule_events",
    "cancel_schedule_event",
    "update_schedule_event",
    "get_schedule_for_date",
    "get_schedule_for_week",
    "format_todays_schedule",
    # Fitness
    "get_current_block",
    "create_override_block",
    "log_session",
    "get_or_create_session",
    "get_recent_sessions",
    "log_exercise",
    "log_exercises_bulk",
    "get_last_weight_for_exercise",
    "create_modification",
    "get_active_modifications",
    "log_weigh_in",
    "get_weight_trend",
    "log_daily_nutrition",
    "log_nutrition_batch",
    "get_nutrition_averages",
    "get_daily_nutrition",
    "log_sleep",
    "get_sleep_average",
    "get_active_deload_cycle",
    "start_deload_cycle",
    "increment_deload_week",
    "complete_deload",
    "format_fitness_summary",
    "format_fitness_detail",
    "get_fitness_prompt",
    "TRAINING_SPLIT",
    "DAY_WEEKDAY_MAP",
]
